// <auto-generated />
using System;
using Component;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Component.Migrations
{
    [DbContext(typeof(ImageResultContext))]
    [Migration("20211215220332_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Component.ImageResultDB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("blob")
                        .HasColumnType("BLOB");

                    b.Property<int>("hash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Component.ObjectsData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageResultDBid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("label")
                        .HasColumnType("TEXT");

                    b.Property<double>("x1")
                        .HasColumnType("REAL");

                    b.Property<double>("x2")
                        .HasColumnType("REAL");

                    b.Property<double>("x3")
                        .HasColumnType("REAL");

                    b.Property<double>("x4")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("ImageResultDBid");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Component.ObjectsData", b =>
                {
                    b.HasOne("Component.ImageResultDB", null)
                        .WithMany("descs")
                        .HasForeignKey("ImageResultDBid");
                });

            modelBuilder.Entity("Component.ImageResultDB", b =>
                {
                    b.Navigation("descs");
                });
#pragma warning restore 612, 618
        }
    }
}
